export const SUBMIT_FORM_DATA = 'SUBMIT_FORM_DATA';
export const LOAD_POSTS = 'LOAD_POSTS';
export const LOAD_POST_BY_ID = 'LOAD_POST_BY_ID';
export const RESET_EDITING = 'RESET_EDITING';
export const SET_EDITING = 'SET_EDITING';
export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const MAKE_COMMENT = 'MAKE_COMMENT';

export const CLEAR_POST = 'CLEAR_POST';

export const SET_RELOAD = 'SET_RELOAD';
export const RESET_RELOAD = 'RESET_RELOAD';
export const TRIGGER_EDITING = 'TRIGGER_EDITING';
export const CLOSE_POST_EDITING = 'CLOSE_POST_EDITING';

export const LIKE_POST = 'LIKE_POST';
export const UNLIKE_POST = 'UNLIKE_POST';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTHENTICATED = 'AUTHENTICATED';


export const LOAD_PROFILE_BY_ID = 'LOAD_PROFILE_BY_ID';
export const LOAD_POST_OF_PROFILE = 'LOAD_POST_OF_PROFILE';
export const CLEAR_PROFILE_STATE = 'CLEAR_PROFILE_STATE';
export const FOLLOW_USER = 'FOLLOW_USER';
export const UNFOLLOW_USER = 'UNFOLLOW_USER';

export const CURRENT_USER = 'CURRENT_USER';
export const EDIT_CURRENT_USER = 'EDIT_CURRENT_USER';